### ISSUE TITLE
Issue with $cacheWrite

### ISSUE THREAD

**Issue by devzom** [ziaadini/nuxt-perfect-cache#5] opened 2021-01-21 11:57 UTC
Another issue I am getting with $cacheWrite
Used as in the example
`const flag = await $cacheWrite({ key:'testKey', expire: 60*60*24 }, 'your content')`

but not working and gave this error
`RedisStore.js?b1a5:101 Uncaught (in promise) TypeError: Cannot read property 'setex' of undefined
    at eval (RedisStore.js?b1a5:101)
    at new Promise (<anonymous>)
    at RedisStore.write (RedisStore.js?b1a5:97)
    at Store.eval [as $cacheWrite] (plugin.js?c34d:10)
    at _callee3$ (categories.js?d4fe:65)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)`

same with 

` const data = await this.$cacheRead({
        key: "testKey"
      })`

**error**

`disconnect not working******** false
RedisStore.js?b1a5:75 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at eval (RedisStore.js?b1a5:75)
    at new Promise (<anonymous>)
    at RedisStore.read (RedisStore.js?b1a5:71)
    at Store.eval [as $cacheRead] (plugin.js?c34d:10)
    at _callee4$ (categories.js?d4fe:65)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)`

what could fix it?

`await this.$cacheFetch(......)` is working perfectly

**Comment by ziaadini** [comment] 2021-02-12 03:49
did you installed latest version of package?

**Comment by devzom** [comment] 2021-02-13 13:10
Yes, of course.
So it didnt' response of 'false' or anything as it couldn't save or read data from Redis cache. It looks like it's not passed correctly, but It was.

**Comment by devzom** [comment] 2021-03-01 07:58
> did you installed latest version of package?

@ziaadini 
from the begining I'm using the newest version available .
anything happened to You like that?

**Comment by ziaadini** [comment] 2021-03-02 04:27
not for this issue, did you check if process is in server?

**Comment by devzom** [comment] 2021-03-04 09:05
Nope, I haven't.
Nothing like that was mentioned in readme

**Comment by ziaadini** [comment] 2021-03-14 07:00
yes, i just forgot document that. did you slove your problem? can i close this issue?

**Comment by devzom** [comment] 2021-05-14 20:16
I see. Unlucky didn't worked for me as You said. Do You have any example in real code of Nuxt project and it's working?

**Comment by peshanghiwa** [comment] 2021-07-13 11:10
latest version*
i do have the same issue

**Comment by ziaadini** [comment] 2021-07-13 14:08
yes i have used it in a real project, and it works as expected.

**Comment by mookapook** [comment] 2021-11-19 06:39
latest version*
i do have the same issue

**Comment by ziaadini** [comment] 2022-01-05 10:14
```
 asyncData() {
    if (process.server) {
    // do wat you want
    }
  }

```
it should works. the problem is you are trying to write in `redis` on client side.
it works only on hard reload.

**Closed as completed by ziaadini** 2022-01-05 10:14 UTC
